### ISSUE TITLE
Privacy issue

### ISSUE THREAD

**Issue by AMRolland** [ismrmrd/siemens_to_ismrmrd#102]
When I try to run a container instance of the converter, I perpetually get the error thrown: "Error response from daemon: pull access denied." How to circumvent this to run/ utilize the tool? I even created a local branch from my clone of the master branch, just in case that the master branch was somehow restricted. Please excuse my very basic question as I am both new to Docker and GitHub. Thank you for any insight.

**Comment by hansenms** [comment]
Please provide steps to reproduce.
