### ISSUE TITLE
Conversion problem with Magnetom Sola data

### ISSUE THREAD

**Issue by jakub-jurek** [ismrmrd/siemens_to_ismrmrd#104]
I have multiple Siemens Magnetom Sola raw files provided by collaborators. I was not present at the time of exporting from the scanner, but I know they were exported as anonymized.

Unfortunately I keep getting an error stating that there is an "Unexpected number of mystery bytes detected: 32". This repeated for AdjFre files, for the ep2d sequence and t2_tse, I guess for others it would be similar. I tried to modify the conversion parameters via supplying non-default xml files but this does not help. My goal is only to get the H5 file, which I will further process in Python in a custom way.

The exact error messages I get are:

WARNING: Unexpected number of mystery bytes detected: 32
ParcFileEntries[0].off_ = 10240
ParcFileEntries[0].len_ = 1127008
siemens_dat.tellg() = 1137216
Please check the result.
WARNING. End of file was not reached during conversion. There are 448 additional bytes at the end of file

With the numbers changing from file to file obviously.
The output .h5 file appears, but is too small (incomplete?). From a 7GB EPI the output is 124 MB for example.

The converter works fine when I try to convert my older files from Siemens Avanto, that were exported from the scanner using twix and "Copy total RAID file" option.

Thank you in advance

**Comment by hansenms** [comment]
@xueh2 or @kspaceKelvin would you guys have any thoughts here.

**Comment by jakub-jurek** [comment]
I tried to open and access data from my .dat files using twixtools (https://github.com/pehses/twixtools). Loading was completed and I could access the headers, acquisition parameters and image data. So I guess the files are correct and its a conversion problem. Still, I would like to use the ismrmrd converter for further processing.

**Comment by jakub-jurek** [comment]
> Alas the mystery bytes remains a mystery to me, but I don't think they affect the conversion.
> 
> Could the issue perhaps be that you're extracting only the dependent data (i.e. AdjFre) from the .dat file? By default, siemens_to_ismrmrd only extracts the first measurement in the file, which are the dependencies if present. You have to explicitly specify the later measurements using the `-z` argument, e.g. `-z 2` for the second measurement in a file. Alternatively you can use the `-Z` option to extract all measurements into a single multi-measurement MRD file.

Brilliant, I think this is the case! Indeed, there were two separate datasets in the file when I used twixtools with the Sola scanner data and one in the Avanto Data. I followed your instruction and managed to export appropriately-looking .h5 files both with -z 1, -z 2 and -Z -M, however I had to specify explicitly the .xsl and .xml files. Still, I get similar messages about mystery bytes, but after reading the converted file with the Ismrmrd Python tools it seems I can access the data now.

Thank you !
