### ISSUE TITLE
MR XA50 "terminate called after throwing an instance of 'std::runtime_error' what(): Malformed file"

### ISSUE THREAD

**Issue by radhikatibrewala** [ismrmrd/siemens_to_ismrmrd#121]
Hello,

We have successfully used the convertor on other various versions/sequences, but we are breaking on XA50 software. Tried multiple fixes including forcing the parameter maps, nothing worked. I loaded the same .dat file in MATLAB to make sure there wasn't any issue with it, and seems not.  I ensured to compile the convertor as recently as it stands today.

I believe @FlorianKnoll had the same issue in 2019 with XA10 (mar19,2019) - closed issue. Could you help or let me know if more changes need to be made for the convertor to work with XA50?

Thanks,
Radhika

**Comment by radhikatibrewala** [comment]
More details on run:
Baseline:
Software version: syngo MR XA50
Protocol name: AX PD FS_SHOULDER_P4_BHS
Dwell time: 6000
Using parameter XSL: IsmrmrdParameterMap_Siemens_NX.xsl
Study time: 17:16:28
terminate called after throwing an instance of 'std::runtime_error'
what(): Malformed file
/cm/local/apps/slurm/var/spool/job21097169/slurm_script: line 23: 98101 Aborted

**Comment by hansenms** [comment]
There is probably not much we can do without an example dataset. Since you say you are compiling the converter yourself, could you do so in debug mode and look at the stack trace and figure out where the error is?

That said, I think this is caused by the converter not being able to read sync data. Flagging for @kspaceKelvin. If you don't need sync data (PMU data), you can skip it `--skipSyncData` and it should work.

**Comment by radhikatibrewala** [comment]
Thank you! You are right, we sourced back the error and it comes from https://github.com/ismrmrd/siemens_to_ismrmrd/blob/master/main.cpp#L1422

which has to do with the PMU data.

I tried your solution:
singularity exec --bind "$DIR":/data --bind "$OUTFILE":/data2 --bind "$DIRMAPS":/data3 sie2ism_v4.sif siemens_to_ismrmrd --skipSyncData  -f /data/"$FILE1" -m  /data3/:IsmrmrdParameterMap_Siemens_v4.xml -x /data3/IsmrmrdParameterMap_Siemens_v4.xsl -o /data2/radhika_checks_work.h5 -z -1 -X

(Im running a dockerised version, its what ive been doing so far so that should not be an issue)

output:
Converting measurement 2 into file /data2/radhika_checks_work.h5 in group dataset
-----------------------------------------------------------------
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load file: /data3/:IsmrmrdParameterMap_Siemens_v4.xml
/cm/local/apps/slurm/var/spool/job21098985/slurm_script: line 27: 29412 Aborted                 singularity exec --bind "$DIR":/data --bind "$OUTFILE":/data2 --bind "$DIRMAPS":/data3 sie2ism_v4.sif siemens_to_ismrmrd --skipSyncData True -f /data/"$FILE1" -m /data3/:IsmrmrdParameterMap_Siemens_v4.xml -x /data3/IsmrmrdParameterMap_Siemens_v4.xsl -o /data2/radhika_checks_work.h5 -z -1 -X

Am I not using the skip line correctly? Thanks again!
