### ISSUE TITLE
Installation instructions missing dependency [+ possible step]

### ISSUE THREAD

**Issue by wtclarke** [ismrmrd/siemens_to_ismrmrd#123]
The installation instructions in the readme of `siemens_to_ismrmrd` is missing a dependency required for `ismrmrd`. 

https://github.com/ismrmrd/siemens_to_ismrmrd/blob/master/README.mkd?plain=1#L29 currently doesn't include `libpugixml-dev` which is included in the [documentation for the `ismrmrd` package](https://ismrmrd.readthedocs.io/en/latest/building.html). `cmake ..` for the package then fails.

Will submit a PR to include.

I also had to run `ldconfig` for the ismrmrd dynamic library to be found, but I'm not sure if that is step specific to my setup.

**Comment by kspaceKelvin** [comment]
Fixed in https://github.com/ismrmrd/siemens_to_ismrmrd/pull/124, thanks!
