### ISSUE TITLE
Last scan not encountered

### ISSUE THREAD

**Issue by chrisdecker1201** [ismrmrd/siemens_to_ismrmrd#16]
Hallo,

I'm really new to all of the ismrmrd stuff but I can't find an answer to my question. Why is the last scan not encountered?

Greets,
chris

**Comment by hansenms** [comment]
Not sure I understand this question. Could you be more specific? What exact problem are you having?

**Comment by chrisdecker1201** [comment]
@hansenms In the main.cpp line 1427 *while (!(last_mask & 1) && //Last scan not encountered*. I have a scan where an additional scan is added at the end where is some information about the UI Configuration. At the moment the siemens_to_ismrmrd Tool just throw away this information that I need.

**Comment by hansenms** [comment]
@chrisdecker1201 well, your sequence probably shouldn't add last scan in acquisition mask to an acquisition that is in fact not the last one in the acquisition. I would probably say that is a bug in the sequence. With that said, we don't always have control over those things ourselves, so you have a couple of options:

1. Simply remove that check in converter. It is open source, so you can edit it. 
2. If you feel that is a generally useful feature, add a command line option to the converter to ignore last in acquisition flag and submit a pull request to have this included. 

Hope this helps?

**Comment by chrisdecker1201** [comment]
@hansenms Okay. Thank you for your answer. I think i will implemente something that give me the convertion of the last scan in an extra file.

**Comment by hansenms** [comment]
@chrisdecker1201 OK, I will close this issue for now.
