### ISSUE TITLE
Help needed in understanding acquisitions from siemens

### ISSUE THREAD

**Issue by chandnisp77** [ismrmrd/siemens_to_ismrmrd#32]
Hello all,

I have a `.dat` file TSE sequence, cartesian trajectory data from a 1.5T Siemens machine. I use `siemens_to_ismrmrd` for converting this data to ISMRMRD format.  The `getNumberOfAcquisitions()` method called on this ISMRMRD dataset returns value 34841 for an encoded space of 640x272x1 (ROXPE1XPE2) with an encoding limit of 0-112-224 (min-centre-max) and 21 slices. The average and repetition values are zeroes. I expected the number of acquisitions as 225 (PE1 lines) x 21 (slices) = 4725.

A random examination of acquired data shows the following pattern:

1.	PE lines 0-96 acquired for slices 0-19 repeatedly 5 times. Data for PE line 97 acquired  only for 0-13 slices repeatedly 5 times (number_of_samples: 512; center_sample: 190). 
2.	PE line 0 acquired for slice 0 continously 22 times (number of samples 1024; center_sample: 0)
3.	PE lines 0-96 acquired for slices 0-19 repeatedly 2 times. Data for PE line 97 acquired  only for 13 slices repeatedly 2 times (number_of_samples: 512; center_sample: 190). 
4.	PE line 94 acquired for slice 0-18 continously 27 times (number_of_samples: 512; center_sample: 256)
5.	PE lines selected randomly (27 Nos.) acquired for slices 0-18  (number_of_samples: 512; center_sample: 256).
6.	PE lines 157-183 acquired for 0-18 slices (number_of_samples: 512; center_sample: 256). 
7.	PE line 94 acquired for slice 0-18 continously 27 times (number_of_samples: 512; center_sample: 256).
8.	PE lines selected randomly (27 Nos.) acquired for slices 0-18 (number_of_samples: 512; center_sample: 256).
9.	PE lines 157-183 acquired for 0-18 slices (number_of_samples: 512; center_sample: 256).
10.	PE line 94 acquired for slice 0-18 continously 27 times (number_of_samples: 512; center_sample: 256).
11.	PE lines selected randomly (27 Nos.) acquired for slices 0-18  (number_of_samples: 512; center_sample: 256).
12.	PE lines 157-183 acquired for 0-18 slices (number_of_samples: 512; center_sample: 256).
13.	PE lines 0-224 acquired for slices 0-20 (number_of_samples: 640; center_sample: 236, channels-5).

I assume that only the data lines (4725 lines) from point (13) represent the actual k-space data. If so, can I have an explanation on remaining data acquisitions (numbered points 1-12). I also examine the flag field in acquisition header. For majority lines flag is set as zero and some lines with flag values 
`ISMRMRD_ACQ_IS_PHASECORR_DATA` or `ISMRMRD_ACQ_FIRST_IN_SLICE` or `ISMRMRD_ACQ_LAST_IN_SLICE`.

Thanks.

**Comment by hansenms** [comment]
Sounds to me like this might be calibration data or something acquired. It’s not really possible for me to interpret whether or not the conversion is correct here. The first thing to do would be to look at the data with the Twix tool and see if those are in fact the lines that are acquired. In other words, I think the converter is just converting what it sees in the file and the interpretation of what that means depends on your sequence.

closing this for now since it’s old.
