### ISSUE TITLE
patient_table_position

### ISSUE THREAD

**Issue by rijobro** [ismrmrd/siemens_to_ismrmrd#42]
We are trying to wrap our head around the geometry in the ISMRMRD header file. For one of our acquisitions has `patient_table_position = (0,0,11750)`, and we've been baffled trying to figure out what the last value represents.

However, looking through the source code, it gets generated here:
https://github.com/ismrmrd/siemens_to_ismrmrd/blob/af3c895aa6027a62cda41bf27a283e5395b0de3f/main.cpp#L893

Does the `TODO` mean that the value cannot be trusted?

**Comment by rajramasawmy** [comment]
Hey, seeing this a bit late.
The table position in siemens_to_ismrmrd refers to the distance the table has moved from its "home" position. 
This behaviour is inconsistent with iceGadgetron. There was discussion here about it (with a relative to iso fix) https://github.com/ismrmrd/siemens_to_ismrmrd/pull/68

**Comment by rijobro** [comment]
@rajramasawmy thanks!
@KrisThielemans not sure if this is still relevant for you or not.
