### ISSUE TITLE
userParameterLong "element is not expected"

### ISSUE THREAD

**Issue by wexeee** [ismrmrd/siemens_to_ismrmrd#54]
Hi,

I'm attempting to run siemens_to_ismrmrd using a modified stylesheet (and map) with the aim of passing spectroscopy relevant parameters through to the xml header in the h5 file.

If I append 

    <xsl:if test="siemens/MEAS/sSpecPara/lVectorSize">  
      <userParameterLong>  
        <name>VectorSize</name>  
          <value>  
            <xsl:value-of select="siemens/MEAS/sSpecPara/lVectorSize"/>  
          </value>  
      </userParameterLong>  
    </xsl:if>

to the end of the userParameters block in IsmrmrdParameterMap_Siemens.xsl (and make the appropriate modifications in the map) I receive the following error.

> element userParameterLong: Schemas validity error : Element '{http://www.ismrm.org/ISMRMRD}userParameterLong': This element is not expected. Expected is one of ( {http://www.ismrm.org/ISMRMRD}userParameterDouble, {http://www.ismrm.org/ISMRMRD}userParameterString, {http://www.ismrm.org/ISMRMRD}userParameterBase64 ).
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Generated XML is not valid according to the ISMRMRD schema
Abort trap: 6

However, if I modify userParameterLong to userParameterDouble or userParameterString I see the parameter in the resulting .h5 file (though as a floating point or string variable).

This would appear to be a bug as the schema [here](https://github.com/ismrmrd/ismrmrd/blob/87b6f6b68fd53702f4f36d1a277ed4b9c865cd26/schema/ismrmrd.xsd) and the embedded version in siemens_to_ismrmrd both list userParameterLong as an acceptable element of the userParameters type (line 237).

I also noticed that the debug xml (processed.xml) isn't generated in this case even with the appropriate -X argument. See line 1478 of [main.cpp](https://github.com/ismrmrd/siemens_to_ismrmrd/blob/3f601092531ac0356d933abb1f4ab58ff97f26e7/main.cpp#L1478).

Relevant files can be downloaded [here](https://1drv.ms/u/s!AnwHLsoRdmW9g8oLErnJ7E6CnDgbcg?e=lCo7rv). The command I am running is:

> siemens_to_ismrmrd -f meas_MID306_sLASER_metab_FID115669.dat -o test.h5 --user-map IsmrmrdParameterMap_Siemens_VB17_svs.xml --user-stylesheet IsmrmrdParameterMap_Siemens_svs.xsl --X

Sorry if I've missed anything obvious. Any help much appreciated.

Will

**Comment by hansenms** [comment]
So I think those parameters are required to come in order...first all the longs, then all the doubles, etc. So if you add a long at the end (after the doubles), it is an error. Add it after the last long and it should work.

**Comment by wexeee** [comment]
You are right. Once I modified the order of the parameters it worked. I thought I had tested whether it was order dependent, but I must have messed up that test somehow. Thanks for the help.
