### ISSUE TITLE
Segments possible bug in xml file

### ISSUE THREAD

**Issue by marcsous** [ismrmrd/siemens_to_ismrmrd#6]
I was looking in the IsmrmrdParameterMap_Siemens.xml and noticed these lines.

```
    <p><s>MEAS.sFastImaging.lShots</s>                          <d>siemens.MEAS.sFastImaging.lSegments</d></p>
    <p><s>MEAS.sFastImaging.lSegments</s>                       <d>siemens.MEAS.sFastImaging.lSegmentSize</d></p>
```

Is that correct? Shots gets mapped to segments? Changing them to

```
    <p><s>MEAS.sFastImaging.lShots</s>                          <d>siemens.MEAS.sFastImaging.lShots</d></p>
    <p><s>MEAS.sFastImaging.lSegments</s>                       <d>siemens.MEAS.sFastImaging.lSegments</d></p>
```

seemed to fix a problem I was having with reading no. segments in gadgetron from Siemens raw data.

For reference, the original thread is here: https://groups.google.com/forum/#!topic/gadgetron/6tKY2a0oyYU

**Comment by hansenms** [comment]
Thanks. There are in fact two bugs. This change has to be done carefully, so we are working on it, but it may not get merged for a few days. You should be able to change it to work for you for now. 

But also, please be aware that the meaning of segment changes from sequence to sequence in Siemens, sometimes they mean shots sometimes lines per shot. In ISMRMRD the meaning of segment is the number of partitions that k-space is divided into. In many sequences in the Siemens world, it is the other way around.

**Comment by hansenms** [comment]
@xueh2 will you take a look at this. We need appropriate fixes on the ICE side too.
