### ISSUE TITLE
Trajectory not appended or even queried

### ISSUE THREAD

**Issue by srapacchi** [ismrmrd/siemens_to_ismrmrd#62]
The trajectory in its 'waveform' form is not queried and thus appended. Currently, only waveforms and trajectory parameters are transfered.

**Comment by hansenms** [comment]
@srapacchi I am closing this for now since it has been inactive for some time. If this is still an issue, please reopen and if it is a bug, it would help with some path to reproducing the problem. If it is a feature request, please explain (in some detail) what the ask is and we will take a look.

**Comment by srapacchi** [comment]
Sorry I am reacting a bit late. I should have been more specific, I will try to reproduce the problem (it has been a while), and re-open the issue once I have confirmed it and, if so, detail steps to reproduce. Thanks.
