### ISSUE TITLE
Problems with extracting data

### ISSUE THREAD

**Issue by thomas-yu-1** [ismrmrd/siemens_to_ismrmrd#97]
I am trying to convert a dataset, but I am unable to, with an error that I have not seen before (Abort due to malformed file). I've attached the log as a png to this post. As the scanner software version was apparently recently updated, I was wondering if this might be the reason? Or perhaps corruption from copying from the scanner?

Thanks in advance. 
![error](https://user-images.githubusercontent.com/14965422/178507225-56909dfe-7d01-4fa7-b858-087ba134f7a0.PNG)

**Comment by hansenms** [comment]
Do you have physio waveforms in the data. The format was recently changed and you may have to skip those (there is a command line switch for that).

**Comment by thomas-yu-1** [comment]
Hi, thanks for the quick response:

I don't believe so, (this was a phantom acquisition), but I am not sure. If so, what would I have to do to skip these?

Thank you.

**Comment by thomas-yu-1** [comment]
From the log, I think the software version is XA 31. 
After trying this, I get new errors attached below:
![error_2](https://user-images.githubusercontent.com/14965422/178562728-6a10bb3b-e335-4160-9963-450982f7144e.PNG)

**Comment by hansenms** [comment]
That error is probably because you are trying to create a file in a write protected location or on top of an existing file.

**Comment by thomas-yu-1** [comment]
Thank you! I'm able to extract the data (as you said this last error was because of trying to write on top of an existing file).
